# Generated by Django 4.2.4 on 2023-08-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='pm',
            field=models.CharField(db_column='PM', max_length=50, primary_key=True, serialize=False),
        ),
    ]
