# Generated by Django 4.2.4 on 2023-08-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_users_username_users_name_alter_users_pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dept',
            field=models.CharField(blank=True, db_column='dept', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='eml',
            field=models.CharField(blank=True, db_column='eml', max_length=50, null=True),
        ),
    ]
