# Generated by Django 4.2.3 on 2023-08-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_users_dept_users_eml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_status',
            field=models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('green', 'green'), ('grey', 'grey')], db_column='Project_status', default='green', max_length=10),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_type',
            field=models.CharField(blank=True, choices=[('SPA', 'SPA'), ('PLP', 'PLP')], db_column='Project_type', max_length=30, null=True),
        ),
    ]
